name: "🚀 release"

on:
    release:
        types: [published]

jobs:
    release:
        name: 🚀 release
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v2.3.4
            - name: 🟢 node
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - name: 🚀 publish
              run: npm publish --access public
              working-directory: src
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
